### ISSUE TITLE
「九九」と入力したところ誤字判定となってしまう

### ISSUE THREAD

**Issue by KentaroTakasaki** [textlint-ja/textlint-rule-ja-no-successive-word#22]
同じ単語（トークン）と判定されてしまったようで、

```"九" が連続して2回使われています。```

というエラーが発生してしまった。

**Comment by azu** [comment]
https://azu.github.io/morpheme-match/?text=%E5%80%A4%E3%81%AF%E4%B9%9D%E4%B9%9D%E3%81%A7%E3%81%99%E3%80%82

「数」は例外するのが良さそうな気がしますね。

**Comment by azu** [comment]
v2.0.1で修正しました
https://github.com/textlint-ja/textlint-rule-ja-no-successive-word/releases/tag/v2.0.1
